config/routes.rb
Rails.application.routes.draw do 
  resources :travelings
  resources :questions
  root 'dashboard#index'
  devise_for :users, 
		:path => "portal",
		controllers: {
			sessions: 'portal/sessions',
			:registrations => "portal/registrations",
			:passwords => "portal/passwords"
		},
		:path_names => { 
			:sign_in => 'login', 
			:sign_out => 'logout'
		}
  resources :users
  resources :tourisms
  resources :roles
	resources :module_labels do
		collection do
			get :filter
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :type_answer
	has_many :points, dependent: :destroy
	has_many :answers, dependent: :destroy	

	accepts_nested_attributes_for :points
	def self.filter(params)
 		condition = []
  		unless params[:name].blank?
  			condition << "LOWER(name) LIKE '%#{params[:name].downcase}%'"
  		end

  		conditions = condition.join(" AND ")

  		query = self.where(conditions)
  		return query
 	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController 
  before_action :new_question, :only => [:create]
  load_and_authorize_resource
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_sidebar
  respond_to :html
  before_action :set_page_title, :set_options

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.filter(params).order("id DESC").page(params[:page]).per(20)
    @questions_all = Question.filter(params)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        @question.points.where("id NOT IN (?)", params[:question][:points_attributes].map{|x| x[1][:id]}).delete_all
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name, :type_answer_id, :description, points_attributes: [:values, :label])
    end

    def new_question
      @question = Question.new(question_params)
    end

    def set_sidebar
      @page_title = "Pertanyaan"
      @page_description = "Untuk Set Pertanyaan"
    end

    def set_page_title
      @open_data_master = "selected active"
      @active_listing_question = "active"
    end

    def set_options
      @type_answers = TypeAnswer.all.order("name ASC")
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/shared/_body_data.html.erb
<% unless @questions.blank? %>
    <% @questions.each_with_index do |question, i| %>
        <tr>
            <td><%= numbering(i, @questions.offset_value) %></td>
            <td><%= question.name %></td>
            <td><%= question.type_answer.name %></td>
            <td><%= question.created_at.strftime("%d/%B/%Y") %></td>
            <td>
                <div class="btn-group btn-group-justified">
                    <%=
                        link_to "<i class='fa fa-eye'></i>".html_safe,
                        question_path(question), title: 'Detail', class: 'btn btn-default'
                    %>
                    <%=
                        link_to "edit".html_safe,
                        edit_question_path(question), title: 'Edit', class: 'btn btn-default'
                    %>
                     <%=
                        link_to "<i class='fa fa-trash'></i>".html_safe, question_path(question),
                        title: 'Hapus', class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' }
                    %>
                </div>
            </td>
        </tr>
    <% end %>
<% else %>
    <tr>
        <th colspan="6"><center>No data Found</center></th>
    </tr>
<% end %>

app/views/questions/shared/_filter.html.erb
<div class="row">
	<!-- <div class="col-lg-12"> -->
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-lg-6">
					<div class="form-group input-group" style="margin:0">
						<%= text_field_tag :name, nil, placeholder: 'Pertanyaan', class: 'form-control' %>
						<span class="input-group-btn">
							<button type="reset" class="btn btn-default reset"><i class="fa fa-refresh"></i></button>
							<button type="button" class="btn btn-primary filters"><i class="fa fa-search"></i></button>
						</span>
					</div>
				</div>
				<div class="col-lg-3 pull-right">
					<%=
						link_to '<i class="fa fa-plus-square"></i> Tambah Pertanyaan'.html_safe,
						new_question_path, class: 'btn btn-success pull-right'
					%>
				</div>
			</div>
		</div>
	<!-- </div> -->
</div>

app/views/questions/shared/_form.html.erb
<div id="error-messages">
  <%= render "shared/error", errors: @question.errors %>
</div>
<%= form_with(model: @question, local: true) do |f| %>  

  <div class="control-group">
    <div class="control-label col-lg-2">
      <%= f.label :name, "Pertanyaan" %>
    </div>
    <div class="controls col-lg-8">
      <%= f.text_field :name, autofocus: true, class:"form-control" %>
    </div>
  </div>
  <div class="clearfix">
    <br><br>
  </div>

  <div class="control-group">
    <div class="control-label col-lg-2">
      <%= f.label :type_answer_id, "Tipe Jawaban" %>
    </div>
    <div class="controls col-lg-4">
      <%= f.select :type_answer_id, options_for_select(@type_answers.map{|x| [x.name, x.id]}.unshift('-Pilih Tipe Jawaban-'), f.object.type_answer_id),{}, class:"form-control" %>
    </div>
  </div>
  <div class="clearfix">
    <br><br>
  </div>
  <div class="control-group" id="point_place"></div>
  <%= f.fields_for :points do |p| %>
    <div class="control-group">
      <div class="control-label col-lg-2">        
        <label>Label</label>
      </div>
      <div class="controls col-lg-3">
        <%= p.text_field :label, autofocus: true, class:"form-control", disabled: f.object.type_answer.name == 'Essay' ? true : false %>
      </div>
      <div class="control-label col-lg-1">
        <label>Point</label>
      </div>
      <div class="controls col-lg-2">
        <%= p.text_field :values, autofocus: true, class:"form-control" %>
      </div>
    </div>
    <div class="clearfix">
      <br><br>
    </div>
  <% end %>  

  <div class="control-group">
    <div class="control-label col-lg-2">
      <%= f.label :description %>
    </div>
    <div class="controls col-lg-8">
      <%= f.text_area :description, autofocus: true, class:"form-control" %>
    </div>
  </div>

  <div class="clearfix">
    <br><br>
  </div>
  <hr>
  <%= f.submit "Simpan", class:"pull-right btn btn-success" %>
  <%= link_to "Kembali", questions_path, class:"btn btn-default" %>
  <div class="clearfix"></div>
<% end %>

app/views/questions/shared/_list.html.erb
<table class="table table-bordered table-hover table-striped tablesorter">
  <thead>
    <tr>
      <th style="width:4%;">No <i class="fa fa-sort pull-right"></i></th>
      <th style="width:18%">Pertanyaan</th>
      <th style="width:20%">Tipe</th>
      <th style="width:10%">Tgl buat</th>      
      <th style="width:10%"></th>
    </tr>
  </thead>
  <tbody id="index_data">
    <%= render "questions/shared/body_data" %>
  </tbody>
</table>