config/routes.rb
Rails.application.routes.draw do 
  resources :travelings
  resources :questions
  root 'dashboard#index'
  devise_for :users, 
		:path => "portal",
		controllers: {
			sessions: 'portal/sessions',
			:registrations => "portal/registrations",
			:passwords => "portal/passwords"
		},
		:path_names => { 
			:sign_in => 'login', 
			:sign_out => 'logout'
		}
  resources :users
  resources :tourisms
  resources :roles
	resources :module_labels do
		collection do
			get :filter
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/traveling.rb
class Traveling < ActiveRecord::Base
	has_many :tourisms, dependent: :destroy

	def self.filter(params)
 		condition = []
  		unless params[:name].blank?
  			condition << "LOWER(name) LIKE '%#{params[:name].downcase}%'"
  		end

  		conditions = condition.join(" AND ")

  		query = self.where(conditions)
  		return query
 	end
end

app/controllers/travelings_controller.rb
class TravelingsController < ApplicationController 
  before_action :new_traveling, :only => [:create]
  load_and_authorize_resource
  before_action :set_traveling, only: [:show, :edit, :update, :destroy]
  before_action :set_sidebar
  respond_to :html

  before_action :set_page_title

  before_action :set_questions, only: [:new, :edit, :create, :update, :show]
  # GET /travelings
  # GET /travelings.json
  def index
    @travelings = Traveling.filter(params).order("id DESC").page(params[:page]).per(20)
    @travelings_all = Traveling.filter(params)
  end

  # GET /travelings/1
  # GET /travelings/1.json
  def show
  end

  # GET /travelings/new
  def new
    @traveling = Traveling.new
  end

  # GET /travelings/1/edit
  def edit
  end

  # POST /travelings
  # POST /travelings.json
  def create
    @traveling = Traveling.new(traveling_params)    
    @traveling.save
    save = Tourism.save_data(params, @traveling)
    respond_to do |format|
      if save
        format.html { redirect_to @traveling, notice: 'Traveling was successfully created.' }
        format.json { render :show, status: :created, location: @traveling }
      else
        format.html { render :new }
        format.json { render json: @traveling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travelings/1
  # PATCH/PUT /travelings/1.json
  def update
    respond_to do |format|
      if @traveling.update(traveling_params)
        save = Tourism.save_data(params, @traveling)
        format.html { redirect_to @traveling, notice: 'Traveling was successfully updated.' }
        format.json { render :show, status: :ok, location: @traveling }
      else
        format.html { render :edit }
        format.json { render json: @traveling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travelings/1
  # DELETE /travelings/1.json
  def destroy
    @traveling.destroy
    respond_to do |format|
      format.html { redirect_to travelings_url, notice: 'Traveling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traveling
      @traveling = Traveling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traveling_params
      params.require(:traveling).permit(:name, :description)
    end

    def new_traveling
      @traveling = Traveling.new(traveling_params)
    end

    def set_sidebar
      @page_title = "Sidak"
      @page_description = "Pariwisata"
    end

    def set_page_title
      @open_sidak = "selected active"
      @active_listing_traveling = "active"
    end

    def set_questions
      @questions = Question.all.order("id ASC")
    end
end

app/helpers/travelings_helper.rb
module TravelingsHelper

	def find_answer(traveling, question, point_id=nil, type_id=0)
		tourisms = Tourism.where(traveling_id: traveling.id, question_id: question.id, point_id: point_id)		
		data_answer = question.points.pluck(:id).include? tourisms.map{|x| x.point_id}.last	
		type_answer = TypeAnswer.where("LOWER(name) like '%multiple choice%'") rescue ""
		if data_answer			
			answer = [tourisms.last.answer,"<div class='col-lg-10 no-padding'>#{tourisms.last.answer}</div> <b>Point :</b> #{tourisms.last.values}".html_safe, tourisms.last.id]			
		else
			answer = [nil,"-", nil]
		end		
		return answer
	end

	def find_single_answer(traveling, question, point_id=nil, type_id=0)
		tourisms = Tourism.where(traveling_id: traveling.id, question_id: question.id, point_id: point_id)		
		data_answer = question.points.pluck(:id).include? tourisms.map{|x| x.point_id}.last	
		type_answer = TypeAnswer.where("LOWER(name) like '%multiple choice%'") rescue ""		
		if data_answer			
			if type_id == type_answer.last.id
				answer = []				
				tourisms.each_with_index do |tourism, index|				
					answer << "<div class='col-lg-10 no-padding'>#{index+1}. <b>#{tourism.point.label}</b> = #{tourisms.last.answer}</div> <b>Point :</b> #{tourism.values}<br>".html_safe
				end
			else
				answer = ["<div class='col-lg-10 no-padding'>#{tourisms.last.answer}</div> <b>Point :</b> #{tourisms.last.values}".html_safe]
			end
		else
			answer = [nil,"-", nil]
		end		
		return answer
	end
end

app/views/travelings/edit.html.erb
<div class="panel panel-default">
      <div class="panel-heading">
          <i class="fa fa-circle"></i> Ubah Pariwisata
      </div>

	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">
				<div>
					<%= render 'travelings/shared/form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/travelings/index.html.erb
<%= render "travelings/shared/filter" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <i class="fa fa-gear"></i> <%= @page_description %>
  </div>

  <div class="panel-body">
    <div class="row">
      <div>
        <div class="table-responsive" id="data-list">
          <%= render "travelings/shared/list" %>
        </div>
      </div>        
      <b>Showing <b class="paging_js_a"><%= @travelings.count %></b> data from <b class="paging_js_b"><%= @travelings_all.count %></b> data</b>
      <span class="pull-right paging_ajax">
        <%= paginate @travelings %>
      </span>     
    </div>
  </div>
</div>

app/views/travelings/index.js.erb
json.array! @travelings, partial: 'travelings/traveling', as: :traveling

app/views/travelings/new.html.erb
<div class="panel panel-default">
      <div class="panel-heading">
          <i class="fa fa-circle"></i> Tambah Pariwisata
      </div>

	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">
				<div>
					<%= render 'travelings/shared/form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/travelings/show.html.erb
<div class="panel panel-default">
      <div class="panel-heading">
          <i class="fa fa-traveling"></i> <%= @page_description %>
      </div>

	<div class="panel-body">
		<div class="row">
			<div class="col-lg-9">
				<div class="control-group">
					<div class="control-label col-lg-4">
						<%= label_tag :name, "Judul SIDAK" %>
					</div>
					<div class="controls col-lg-8">
						<%= @traveling.name %>
					</div>
				</div>
				<div class="clearfix"></div>

				<% @questions.each do |question| %>
					<div class="control-group">
						<div class="control-label col-lg-4">
							<%= label_tag :question, question.name %>
						</div>
						<div class="controls col-lg-8">
							<% find_single_answer(@traveling,question, question.points.pluck(:id), question.type_answer_id).each do |my| %>
								<%= my %>
							<% end %>
						</div>
					</div>
					<div class="clearfix"></div>
				<% end %>
				
				<div class="control-group">
					<div class="control-label col-lg-4">
						<%= label_tag :description,"Deskripsi" %>
					</div>
					<div class="controls col-lg-8">
						<%= @traveling.description.blank? ? "-" : @traveling.description.html_safe %>
					</div>
				</div>
			</div>			
			<div class="col-lg-3">
				<div class="form-group pict_box pull-right">
					<div class="foto_prev">
						
					</div>
				</div>
			</div>				
			<div class="clearfix"></div>
			<hr>
			<%= link_to "Edit", edit_traveling_path(@traveling), class:"pull-right btn btn-primary" %>
			<%= link_to "Kembali", travelings_path, class:"btn btn-default" %>
		</div>
	</div>
</div>